# Generated by Django 5.0 on 2023-12-04 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenities',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
