# Generated by Django 5.0 on 2023-12-06 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contactus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactUs',
            new_name='Booking',
        ),
    ]
