# Generated by Django 5.0 on 2023-12-06 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_contactus_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
